list: $/pbs/products/models/item/columns.yaml
modelClass: Pbs\Products\Models\Item
title: Items
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pbs/products/items/update/:id'
