list: $/pbs/products/models/variant/columns.yaml
modelClass: Pbs\Products\Models\Variant
title: Variants
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pbs/products/variants/update/:id'
